# Generated by Django 2.0.4 on 2018-04-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djdelt', '0002_auto_20180420_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gkgdocument',
            name='v2counts',
            field=models.TextField(blank=True),
        ),
    ]
