# Generated by Django 2.0.4 on 2018-04-20 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djdelt', '0003_auto_20180420_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gkgdocument',
            name='gkg_record_id',
            field=models.CharField(max_length=20),
        ),
    ]
