# Generated by Django 2.0.4 on 2018-04-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djdelt', '0004_auto_20180420_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='gkgdocument',
            name='gcam',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gkgdocument',
            name='dates',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gkgdocument',
            name='tone',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gkgdocument',
            name='v1locations',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gkgdocument',
            name='v1organizations',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gkgdocument',
            name='v1persons',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gkgdocument',
            name='v1themes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gkgdocument',
            name='v2locations',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gkgdocument',
            name='v2organizations',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gkgdocument',
            name='v2persons',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gkgdocument',
            name='v2themes',
            field=models.TextField(blank=True),
        ),
    ]
