# Generated by Django 2.0.4 on 2018-04-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djdelt', '0005_auto_20180420_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='gkgdocument',
            name='sharing_image',
            field=models.URLField(blank=True),
        ),
    ]
