# Generated by Django 2.0.4 on 2018-04-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djdelt', '0013_gkgdocument_translation_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='gkgdocument',
            name='extras_xml',
            field=models.TextField(blank=True),
        ),
    ]
