# Generated by Django 2.0.4 on 2018-04-21 22:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('djdelt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gkgdocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 4, 21, 22, 4, 10, 928977, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
