# Generated by Django 2.0.4 on 2018-04-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djdelt', '0002_gkgdocument_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gkgdocument',
            name='sharing_image',
            field=models.URLField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='gkgmedia',
            name='url',
            field=models.URLField(max_length=1024),
        ),
    ]
