# Generated by Django 2.0.4 on 2018-04-27 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djdelt', '0003_auto_20180423_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='gkgdocument',
            name='html',
            field=models.TextField(blank=True),
        ),
    ]
