# Generated by Django 2.0.4 on 2018-04-27 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djdelt', '0004_gkgdocument_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='gkgdocument',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
