# Generated by Django 2.0.4 on 2018-04-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djdelt', '0005_gkgdocument_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='gkgdocument',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
