# Generated by Django 2.0.4 on 2018-04-20 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djdelt', '0006_gkgdocument_sharing_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GKGImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
            ],
        ),
    ]
