# Generated by Django 2.0.4 on 2018-04-20 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djdelt', '0007_gkgimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gkgimage',
            name='url',
            field=models.URLField(),
        ),
    ]
