# Generated by Django 2.0.4 on 2018-04-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djdelt', '0007_auto_20180427_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gkgdocument',
            name='document_identifier',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='gkgdocument',
            name='source_collection',
            field=models.IntegerField(blank=True, choices=[(1, 'Web'), (2, 'Citation only'), (3, 'Core'), (4, 'DTIC'), (5, 'JSTOR'), (6, 'Non-textual')], null=True),
        ),
        migrations.AlterField(
            model_name='gkgdocument',
            name='source_common_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
