# Generated by Django 2.0.4 on 2018-04-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djdelt', '0008_auto_20180427_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='gkgdocument',
            name='title',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
