# Generated by Django 2.0.4 on 2018-04-20 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djdelt', '0008_auto_20180420_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='gkgimage',
            name='document',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='djdelt.GKGDocument'),
            preserve_default=False,
        ),
    ]
