# Generated by Django 2.0.4 on 2018-04-20 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djdelt', '0009_gkgimage_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djdelt.GKGDocument')),
            ],
        ),
    ]
