# Generated by Django 2.0.4 on 2018-04-29 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djdelt', '0009_gkgdocument_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gkgdocument',
            name='html',
        ),
        migrations.RemoveField(
            model_name='gkgdocument',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='gkgdocument',
            name='text',
        ),
        migrations.RemoveField(
            model_name='gkgdocument',
            name='title',
        ),
    ]
