# Generated by Django 2.0.4 on 2018-04-21 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djdelt', '0010_socialimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='gkgdocument',
            name='all_names',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gkgdocument',
            name='quotations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='socialvideo',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djdelt.GKGDocument'),
        ),
    ]
