# Generated by Django 2.0.4 on 2018-04-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djdelt', '0012_gkgdocument_amounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='gkgdocument',
            name='translation_info',
            field=models.TextField(blank=True),
        ),
    ]
