# Generated by Django 2.0.4 on 2018-04-21 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djdelt', '0014_gkgdocument_extras_xml'),
    ]

    operations = [
        migrations.CreateModel(
            name='GKGMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('media_type', models.CharField(max_length=18)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djdelt.GKGDocument')),
            ],
        ),
    ]
