# Generated by Django 2.0.4 on 2018-04-21 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djdelt', '0016_auto_20180421_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gkgdocument',
            name='id',
        ),
        migrations.AlterField(
            model_name='gkgdocument',
            name='gkg_record_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
